default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

Pyramids:
    summary_freq: 30000
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 1.0e7
    num_epoch: 3
    behavioral_cloning:
        demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo
        strength: 0.5
        steps: 150000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: Project/Assets/ML-Agents/Examples/Pyramids/Demos/ExpertPyramid.demo

CrawlerStatic:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    max_steps: 1e7
    summary_freq: 30000
    num_layers: 3
    hidden_units: 512
    behavioral_cloning:
        demo_path: Project/Assets/ML-Agents/Examples/Crawler/Demos/ExpertCrawlerSta.demo
        strength: 0.5
        steps: 50000
    reward_signals:
        extrinsic: #neither was this?
            strength: 1.0
            gamma: 0.99
        curiosity: #wasn't here before
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            #strength: 1.0
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: Project/Assets/ML-Agents/Examples/Crawler/Demos/ExpertCrawlerSta.demo

PushBlock:
    max_steps: 1.5e7
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 60000
    time_horizon: 64
    num_layers: 2
    behavioral_cloning: #not here
        demo_path: Project/Assets/ML-Agents/Examples/PushBlock/Demos/ExpertPush.demo
        #strength: 1.0
        #steps: 0
        strength: 0.5
        steps: 6000
    reward_signals:
        extrinsic: #not here
            strength: 1.0
            gamma: 0.99
        curiosity: #not here
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01 #1.0
            gamma: 0.99
            encoding_size: 128
            demo_path: Project/Assets/ML-Agents/Examples/PushBlock/Demos/ExpertPush.demo

Hallway:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    num_epoch: 3
    buffer_size: 1024
    batch_size: 128
    max_steps: 1.0e7
    summary_freq: 10000
    time_horizon: 64
    behavioral_cloning:
        demo_path: Project/Assets/ML-Agents/Examples/Hallway/Demos/ExpertHallway.demo
        strength: 0.5
        steps: 7000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity: #not here
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
            demo_path: Project/Assets/ML-Agents/Examples/Hallway/Demos/ExpertHallway.demo

FoodCollector:
    batch_size: 64
    max_steps: 2.0e6
    use_recurrent: false
    hidden_units: 128
    learning_rate: 3.0e-4
    num_layers: 2
    sequence_length: 32
    behavioral_cloning:
        demo_path: Project/Assets/ML-Agents/Examples/FoodCollector/Demos/ExpertFood.demo
        #strength: 1.0
        #steps: 0
        strength: 0.5
        steps: 5000
    reward_signals:
        extrinsic: #wasn't here before!
            strength: 1.0
            gamma: 0.99
        curiosity: #wasn't here before
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
            demo_path: Project/Assets/ML-Agents/Examples/FoodCollector/Demos/ExpertFood.demo
    
