default:
    trainer: ppo
    batch_size: 128
    beta: 1.0e-2
    buffer_size: 2048
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e5
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 2000
    use_recurrent: false
    behavioral_cloning:
        demo_path: ./demos/MyDemoTest.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: demos/MyDemoTest.demo